### ISSUE TITLE
Wrong return type for `scipy.fft.next_fast_len`

### ISSUE THREAD

**Issue by martin-ruffel-sncf** [jorenham/scipy-stubs#163]
`scipy.fft.next_fast_len` and `scipy.fft.prev_fast_len` are supposed to return an `int`
https://github.com/jorenham/scipy-stubs/blob/654a7eff410d46d27aaad9d4485993c6b926606c/scipy-stubs/fft/_helper.pyi#L12-L13

I am not sure whether this has to be corrected in scipy directly, this comes from the way the functions are defined:
https://github.com/scipy/scipy/blob/main/scipy/fft/_helper.py#L10-L66

**Comment by jorenham** [comment]
The documentation indeed says that they should return an `int`, but because their function bodies both only contain a `pass` statement, they always return `None` in practice.

Strange stuff 🤔 

It looks to me like these are intended to represent something akin to abstract methods. But seeing as there's no class that these function live in; the only way we could type it is as it's currently types, i.e. returning `None` 🤷🏻.

So you could raise this at scipy, and ask for clarification. If you do so, could you tag me or this issue?

**Comment by jorenham** [comment]
Ohh I missed that part! 
That changes things, because then this is indeed a `scipy-stubs` issue 😅.

```pycon
>>> from scipy.fft import next_fast_len, prev_fast_len
>>> next_fast_len(42)
42
>>> prev_fast_len(42)
42
```
